version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3001:3001"

  frontend:
    build: ./apps/frontend
    volumes:
      - ./apps/frontend:/app           
      - /app/node_modules              
    ports:
      - "3000:3000"                    
    environment:
      - CHOKIDAR_USEPOLLING=true       
      - WDS_SOCKET_PORT=3000           
    stdin_open: true                   
    tty: true                          